### ISSUE TITLE
In Python 3.7 `async` is now protected causing build errors

### ISSUE THREAD

**Issue by jyontz** [raisjn/pudgy#1]
File: pudgy/components/bigpipe.py
Class Pagelet has method `async()` which gives an error when trying to run `snorkel` commands

`Traceback (most recent call last):
  File "/Users/jyontz/anaconda3/bin/snorkel.frontend", line 6, in <module>
    import snorkel
  File "/Users/jyontz/anaconda3/lib/python3.7/site-packages/snorkel/__init__.py", line 3, in <module>
    from . import main
  File "/Users/jyontz/anaconda3/lib/python3.7/site-packages/snorkel/main.py", line 10, in <module>
    from . import web
  File "/Users/jyontz/anaconda3/lib/python3.7/site-packages/snorkel/web.py", line 1, in <module>
    import pudgy
  File "/Users/jyontz/anaconda3/lib/python3.7/site-packages/pudgy/__init__.py", line 1, in <module>
    from .blueprint import register_blueprint, compress_request
  File "/Users/jyontz/anaconda3/lib/python3.7/site-packages/pudgy/blueprint.py", line 25, in <module>
    from . import prelude, util, components
  File "/Users/jyontz/anaconda3/lib/python3.7/site-packages/pudgy/prelude.py", line 1, in <module>
    from . import components, util
  File "/Users/jyontz/anaconda3/lib/python3.7/site-packages/pudgy/components/__init__.py", line 1, in <module>
    from .exported import *
  File "/Users/jyontz/anaconda3/lib/python3.7/site-packages/pudgy/components/exported.py", line 27, in <module>
    from .bigpipe import Pipeline, Pagelet, NoJSPagelet
  File "/Users/jyontz/anaconda3/lib/python3.7/site-packages/pudgy/components/bigpipe.py", line 138
    def async(self):
            ^
SyntaxError: invalid syntax`

**Comment by okayzed** [comment]
Oof - thanks for telling me about this. I had been testing on python2.7 and python3.6
